services:
  infinispan:
    container_name: infinispan-mcp
    image: quay.io/infinispan/server:16.2
    ports:
      - "11222:11222"
    environment:
      - USER=admin
      - PASS=password
      - JAVA_OPTIONS=-Dorg.infinispan.feature.mcp=true
    command: -c infinispan-dev-mode.xml
