// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: vector-search/proto/beer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Beer struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Style                string                 `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	Brewery              string                 `protobuf:"bytes,3,opt,name=brewery,proto3" json:"brewery,omitempty"`
	Country              string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Abv                  float64                `protobuf:"fixed64,5,opt,name=abv,proto3" json:"abv,omitempty"`
	Description          string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	DescriptionEmbedding []float32              `protobuf:"fixed32,7,rep,packed,name=descriptionEmbedding,proto3" json:"descriptionEmbedding,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Beer) Reset() {
	*x = Beer{}
	mi := &file_vector_search_proto_beer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Beer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beer) ProtoMessage() {}

func (x *Beer) ProtoReflect() protoreflect.Message {
	mi := &file_vector_search_proto_beer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beer.ProtoReflect.Descriptor instead.
func (*Beer) Descriptor() ([]byte, []int) {
	return file_vector_search_proto_beer_proto_rawDescGZIP(), []int{0}
}

func (x *Beer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Beer) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *Beer) GetBrewery() string {
	if x != nil {
		return x.Brewery
	}
	return ""
}

func (x *Beer) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Beer) GetAbv() float64 {
	if x != nil {
		return x.Abv
	}
	return 0
}

func (x *Beer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Beer) GetDescriptionEmbedding() []float32 {
	if x != nil {
		return x.DescriptionEmbedding
	}
	return nil
}

var File_vector_search_proto_beer_proto protoreflect.FileDescriptor

const file_vector_search_proto_beer_proto_rawDesc = "" +
	"\n" +
	"\x1evector-search/proto/beer.proto\x12\n" +
	"quickstart\"\xcc\x01\n" +
	"\x04Beer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05style\x18\x02 \x01(\tR\x05style\x12\x18\n" +
	"\abrewery\x18\x03 \x01(\tR\abrewery\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x10\n" +
	"\x03abv\x18\x05 \x01(\x01R\x03abv\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x122\n" +
	"\x14descriptionEmbedding\x18\a \x03(\x02R\x14descriptionEmbeddingB1Z/infinispan.org/tutorials/go/vector-search/protob\x06proto3"

var (
	file_vector_search_proto_beer_proto_rawDescOnce sync.Once
	file_vector_search_proto_beer_proto_rawDescData []byte
)

func file_vector_search_proto_beer_proto_rawDescGZIP() []byte {
	file_vector_search_proto_beer_proto_rawDescOnce.Do(func() {
		file_vector_search_proto_beer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_search_proto_beer_proto_rawDesc), len(file_vector_search_proto_beer_proto_rawDesc)))
	})
	return file_vector_search_proto_beer_proto_rawDescData
}

var file_vector_search_proto_beer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vector_search_proto_beer_proto_goTypes = []any{
	(*Beer)(nil), // 0: quickstart.Beer
}
var file_vector_search_proto_beer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vector_search_proto_beer_proto_init() }
func file_vector_search_proto_beer_proto_init() {
	if File_vector_search_proto_beer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_search_proto_beer_proto_rawDesc), len(file_vector_search_proto_beer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vector_search_proto_beer_proto_goTypes,
		DependencyIndexes: file_vector_search_proto_beer_proto_depIdxs,
		MessageInfos:      file_vector_search_proto_beer_proto_msgTypes,
	}.Build()
	File_vector_search_proto_beer_proto = out.File
	file_vector_search_proto_beer_proto_goTypes = nil
	file_vector_search_proto_beer_proto_depIdxs = nil
}
