[id='hotrod-cpp-tutorials_{context}']
= Hot Rod C{plusplus} client tutorials

[discrete]
== Prerequisites

* Centos 7 (RHEL 7 should work also)
* {brandname} Server running with the default standalone configuration

[discrete]
== Docker
Here is a easy way to setup a Docker container running Centos 7, so you can run the
tutorial in a confined environment.

[discrete]
=== Setup the Server

On the host machine, start at least one {brandname} Server instance.

Create a default cache

    curl -vvvv -X POST http://127.0.0.1:11222/rest/v2/caches/default

Change to this README directory, download the client .rpm

    wget https://downloads.jboss.org/infinispan/HotRodCPP/8.3.1.Final/infinispan-hotrod-cpp-8.3.1.Final-RHEL-x86_64.rpm
Start the Centos Docker container

    docker run -i -t -v $PWD:/home/infinispan/git/infinispan-simple-tutorial:Z --network="host" centos:7

[discrete]
=== On the Container

[discrete]
==== Build the client
    cd /home/infinispan/git/infinispan-simple-tutorial/c++
    yum install wget unzip cmake make gcc-c++ protobuf-devel cyrus-sasl-devel
    rpm -i --force infinispan-hotrod-cpp-8.3.1.Final-RHEL-x86_64.rpm
    mkdir build && pushd build
    cmake ..
    cmake --build .

[discrete]
==== Run the client
    LD_LIBRARY_PATH=/usr/lib ./simple
