[id='remote-tutorials_{context}']
= Remote cache tutorials

To run these tutorials you need at least one locally running instance of {brandname} Server.

To run the Server as a container image, visit the "Get Started" page
in the {brandname} Website:

link:https://infinispan.org/get-started/[Get Started with {brandname}]

You can always link:https://infinispan.org/download/[download] the latest server distribution and run from the downloaded files:

[source,bash,options="nowrap",subs=attributes+]
----
$ ./bin/cli.sh user create admin -p "password"
$ ./bin/server.sh
----

.{brandname} credentials and permission

{brandname} Server enables authentication and authorization by default.
Creating a user named `admin` gives you administrative access to Infinispan Server.
You can find more details about users and permissions in link:{server_docs}#creating-users_quickstart[Creating and Modifying Users]

You can build and run remote cache tutorials directly in your IDE or from the command line as follows:

[source,bash,options="nowrap",subs=attributes+]
----
$ mvn clean package exec:exec
----
