[id='hotrod-dotnet-tutorials_{context}']
= Hot Rod .NET/C# client tutorials

[discrete]
== Prerequisites

* .NET C# Client assembly. You can get it either:
**  from source https://github.com/infinispan/dotnet-client
**  from install pack http://infinispan.org/hotrod-clients/

[discrete]
== Running the example
Do one of the following (1,2 may be suitable for devs while 3 is for runtime):

. Copy in this directory (aside this README.md) the following dlls:
- hotrodcs.dll
- hotrod.dll
- hotrod_wrap.dll
- libeay32.dll (SSL stuff)
- ssleay32.dll (SSL stuff)

. Update dlls location in simple.csproj with the right paths in your file system

. Install the binary client on the machine, update the PATH env. variable to include the bin and lib directories of the installed pack, install your application.

[TIP]
====
HINT THAT CAN SAVE YOU A LOT OF TIME: the .csproj at build time will copy the dlls into the output directory aside the application,
this is the simplest way to run the example without changing your setting (PATH variable).
As a general rule remember that the unmanaged libraries (hotrod_wrap, hotrod, libeay32, libssl32)
must be either in the PATH or in the application working directory.
====
