# tag::config[]
infinispan.remote.server-list=127.0.0.1:11222
infinispan.remote.reactive=true

# Protobuf schemas are automatically discovered and uploaded to the server at startup.
# To disable this behavior, uncomment the following property:
# infinispan.remote.use-schema-registration=false
# end::config[]
