# tag::config[]
infinispan.remote.connection-uri=hotrod://admin:password@127.0.0.1:11222

# Per-cache configuration: point to the cache XML definition and ProtoStreamMarshaller marshaller
infinispan.remote.cache.characters.configuration-uri=classpath:indexedCache.xml
infinispan.remote.cache.characters.marshaller=org.infinispan.commons.marshall.ProtoStreamMarshaller

characters.filename=characters.csv

# Protobuf schemas are automatically discovered and uploaded to the server at startup.
# To disable this behavior, uncomment the following property:
# infinispan.remote.use-schema-registration=false
# end::config[]
