= Replicated Cache with Embedded Infinispan
:summary: Create a replicated synchronous cache where all data is stored on every node in the cluster
:mode: embedded
:topics: caching,clustering
:keywords: replicated,cluster,embedded,cache-mode,repl-sync
:duration: 10
:source-dir: infinispan-embedded/cache-replicated

TIP: The source code for this tutorial is available on link:https://github.com/infinispan/infinispan-simple-tutorials/tree/main/{source-dir}[GitHub].

== What You Will Learn

How to create a clustered Infinispan cache in replicated synchronous mode, where every entry is copied to all nodes in the cluster.

== Prerequisites

* Java 17+

== Step 1: Add the Embedded Dependency

Add Infinispan core to your `pom.xml`:

[source,xml]
----
<dependency>
   <groupId>org.infinispan</groupId>
   <artifactId>infinispan-core</artifactId>
</dependency>
----

== Step 2: Create a Replicated Cache

Set up a clustered cache manager and configure a cache with `REPL_SYNC` mode. Every entry is synchronously replicated to all nodes:

[source,java]
----
include::src/main/java/org/infinispan/tutorial/simple/replicated/InfinispanReplicated.java[tag=create-cache]
----

== Step 3: Populate and Query the Cache

Store entries and observe that each node holds all the data. Use `SKIP_REMOTE_LOOKUP` to see the local view:

[source,java]
----
include::src/main/java/org/infinispan/tutorial/simple/replicated/InfinispanReplicated.java[tag=put-get]
----

In replicated mode, both views show the same entries because every node has a full copy of the data.

== Step 4: Run the Tutorial

[source,bash]
----
mvn package exec:java
----

The local and cluster-wide views will display the same entries, unlike distributed mode where data is partitioned.

== What's Next

* Compare with link:/tutorials/embedded-cache-distributed/[distributed mode] where data is partitioned
* Try link:/tutorials/embedded-cache-invalidated/[invalidation mode] for locally-managed data
* Use link:/tutorials/embedded-streams/[distributed streams] for parallel processing
