= Remote caches with TLS (SSL) encryption and security authorization

**Authors:** Wolf Fink +
**Technologies:** Infinispan, Hot Rod, Java, SSL/TLS, RBAC +
**Summary:** Use SSL/TLS certificates to verify Hot Rod client identities and encrypt network traffic to the server. This tutorial also demonstrates how to perform client certificate authentication and use security authorization with client certificates.

== Build instructions and preparation

. Install Java 11 or later.
+
This tutorial requires Java 11 at minimum.
+
To complete these procedures, you need to generate TLS artifacts with the Java keytool, including certificates, keystores, and trust stores.
+
The example keystores and trust stores are in PKCS12 format, which is the recommended standard.
If you attempt to generate the TLS artifacts with older Java versions, you get prompted for missing arguments and keytool commands fail.

. Build the project.
+
----
$ mvn clean package
----
+
NOTE: The certificates are build and removed by maven with the goals clean and package.
If you are interested how the keytool is used see the create_*.sh scripts.
+
. Download and start at least one Infinispan Server instance.

== Unsigned Server certificates

. Copy `server-keystore.pfx` to `$ISPN_HOME/server/conf`.
. Copy `server/infinispan-uCert.xml` to `$ISPN_HOME/server/conf`.
+
The `infinispan-uCert.xml` configuration applies the following changes:
+
Note that the default properties realm is removed.
+
[source,xml]
----
<security-realm name="default">
  <server-identities>
    <ssl>
      <keystore path="server-keystore.pfx"
                keystore-password="secret"
                alias="infinispan-server"/>
    </ssl>
  </server-identities>
</security-realm>
----
+
[source,xml]
----
<distributed-cache name="secured" mode="SYNC">
  <encoding media-type="application/x-protostream"/>
</distributed-cache>
----
+
. Start the server with the `infinispan-uCert.xml` configuration.
+
[source]
----
$ $ISPN_HOME/bin/server.sh -c infinispan-uCert.xml
----
+
. Run the client.
+
[source]
----
$ export TEST=SIMPLE && mvn exec:exec@run
----
. Check server logs to verify that the PUT and GET requests succeed.

=== Unsigned server certificates with client authorization

Add security authorization to assign client permissions based on TLS identities.

. Copy `client-truststore.pfx` to `$ISPN_HOME/server/conf`.
. Copy `server/infinispan-uCertAuth.xml` to `$ISPN_HOME/server/conf`.
+
The `infinispan-uCertAuth.xml` configuration applies the following changes:
+
[source,xml]
----
<endpoints socket-binding="default"
           security-realm="default"
           require-ssl-client-auth="true"/>
----
+
[source,xml]
----
<security-realm name="default">
  <server-identities>
    <ssl>
      <keystore path="server-keystore.pfx"
                keystore-password="secret"
                alias="infinispan-server"/>
      <truststore path="client-truststore.pfx"
                  password="ClientSecret"/>
    </ssl>
  </server-identities>
  <truststore-realm/>
</security-realm>
----
+
[source,xml]
----
<cache-container>
  <security>
    <authorization>
      <common-name-role-mapper/>
      <!-- In this example `Client1` and `Client2` correspond to the `cn` field in client certificates -->
      <role name="Client1" permissions="ALL"/>
      <role name="Client2" permissions="READ"/>
    </authorization>
  </security>
</cache-container>
----
+
[source,xml]
----
<distributed-cache name="secured" mode="SYNC">
  <encoding media-type="application/x-protostream"/>
  <security>
    <authorization/>
  <security>
</distributed-cache>
----
+
. Start the server with the `infinispan-uCertAuth.xml` configuration.
+
[source]
----
$ $ISPN_HOME/bin/server.sh -c infinispan-uCertAuth.xml
----
+
. Run the clients. Values for test are the enum values SSLConfig, comma separated.
+
[source]
----
$ export TEST=SIMPLEAUTH1,SIMPLEAUTH2 && mvn exec:exec@run
----
. Check the server logs.
+
PUT and GET requests succeed for Client1 which has ALL permissions.
However, Client2 does not have WRITE permission to the cache so the client returns an error.

== Signed server keystore with client certificate verification

Using certificates signed by a public CA means that Infinispan Server does not need a trust store that contains all public client certificates.
If the trust store contains only the CA certificate then Infinispan Server can trust any client certificates that are signed by the CA.

. Copy `server_keystore.p12` and `server_truststore.p12` to `$ISPN_HOME/server/conf`.
. Copy `server/infinispan-sCert.xml` to `$ISPN_HOME/server/conf`.
+
The `infinispan-sCert.xml` configuration applies the following changes:
+
[source,xml]
----
<security-realm name="default">
  <server-identities>
    <ssl>
      <keystore path="server_keystore.p12"
                keystore-password="Serversecret"
                alias="infinispan-server"/>
      <truststore path="server_truststore.p12"
                  password="ServerTrustsecret"/>
    </ssl>
  </server-identities>
</security-realm>
----
+
[source,xml]
----
<endpoints socket-binding="default"
           security-realm="default"
           require-ssl-client-auth="true"/>
----
+
[source,xml]
----
<distributed-cache name="secured" mode="SYNC">
  <encoding media-type="application/x-protostream"/>
</distributed-cache>
----
+
. Start the server with the `infinispan-sCert.xml` configuration.
+
[source]
----
$ $ISPN_HOME/bin/server.sh -c infinispan-sCert.xml
----
+
. Run the clients.
+
[source]
----
$ export TEST=CLIENT1,CLIENT2 && mvn exec:exec@run
----
+
. Check server logs to verify that the PUT and GET requests succeed.

=== Signed Server certificates with client certificate authentication and authorization

Add security authorization to assign client permissions based on TLS identities.

. Copy `server_keystore.p12` and `server_truststore.p12` to `$ISPN_HOME/server/conf`.
. Copy `server/infinispan-sCertAuth.xml` to `$ISPN_HOME/server/conf`.
+
The `infinispan-sCertAuth.xml` configuration applies the following changes:
+
[source,xml]
----
<cache-container>
  <security>
    <authorization>
      <!-- In this example `Client1` and `Client2` correspond to the `cn` field in client certificates -->
      <common-name-role-mapper/>
      <role name="Client1" permissions="ALL"/>
      <role name="Client2" permissions="READ"/>
    </authorization>
  </security>
</cache-container>
----
+
[source,xml]
----
<distributed-cache name="secured" mode="SYNC">
  <encoding media-type="application/x-protostream"/>
  <security>
    <authorization/>
  <security>
</distributed-cache>
----
+
[source,xml]
----
<security-realm name="default">
  <server-identities>
    <ssl>
      <keystore path="server_keystore.p12"
                keystore-password="Serversecret"
                alias="infinispan-server"/>
      <truststore path="server_truststore.p12"
                  password="ServerTrustsecret"/>
    </ssl>
  </server-identities>
  <truststore-realm/>
</security-realm>
----
+
[source,xml]
----
<endpoints socket-binding="default"
           security-realm="default"
           require-ssl-client-auth="true"/>
----
+
. Start the server with the `infinispan-sCertAuth.xml` configuration.
+
[source]
----
$ $ISPN_HOME/bin/server.sh -c infinispan-sCertAuth.xml
----
+
. Run the clients.
+
[source]
----
$ export TEST=CLIENT1AUTH,CLIENT2AUTH && mvn exec:exec@run
----

Client requests fail because the `<truststore-realm/>` element is now included in the security realm configuration.
This enforces client certificate authentication so that the trust store must contain all public certificates, not just the CA chain.

Continue with the following steps to complete the tutorial:

. Copy `server_truststoreAuth.p12` to `$ISPN_HOME/server/conf` and update the truststore configuration as follows:
+
[source,xml]
----
<security-realm name="default">
  <server-identities>
    <ssl>
      <keystore .../>
      <truststore path="server_truststoreAuth.p12"
                  password="ServerTrustsecret"/>
    ...
----
+
. Run the clients.
+
[source]
----
$ export TEST=CLIENT1AUTH,CLIENT2AUTH && mvn exec:exec@run
----
+
. Check the server logs.
+
PUT and GET requests succeed for Client1 which has ALL permissions.
However, Client2 does not have WRITE permission to the cache so the client returns an error.

== Troubleshooting

To debug failures, enable `org.wildfly.security` and `org.infinispan.security` logging with TRACE level messages.

Note that `mvn clean` will delete the certificates, a new build will create it but they are then different and the connection to an existing server with older certificates will fail.

Consider that running the client needs `mvn exec:exec@run` to not fail as there are multiple executions defined.
