// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: continuous-query/proto/instapost.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstaPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Hashtag       string                 `protobuf:"bytes,3,opt,name=hashtag,proto3" json:"hashtag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstaPost) Reset() {
	*x = InstaPost{}
	mi := &file_continuous_query_proto_instapost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstaPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstaPost) ProtoMessage() {}

func (x *InstaPost) ProtoReflect() protoreflect.Message {
	mi := &file_continuous_query_proto_instapost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstaPost.ProtoReflect.Descriptor instead.
func (*InstaPost) Descriptor() ([]byte, []int) {
	return file_continuous_query_proto_instapost_proto_rawDescGZIP(), []int{0}
}

func (x *InstaPost) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstaPost) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *InstaPost) GetHashtag() string {
	if x != nil {
		return x.Hashtag
	}
	return ""
}

var File_continuous_query_proto_instapost_proto protoreflect.FileDescriptor

const file_continuous_query_proto_instapost_proto_rawDesc = "" +
	"\n" +
	"&continuous-query/proto/instapost.proto\x12\btutorial\"I\n" +
	"\tInstaPost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x18\n" +
	"\ahashtag\x18\x03 \x01(\tR\ahashtagB4Z2infinispan.org/tutorials/go/continuous-query/protob\x06proto3"

var (
	file_continuous_query_proto_instapost_proto_rawDescOnce sync.Once
	file_continuous_query_proto_instapost_proto_rawDescData []byte
)

func file_continuous_query_proto_instapost_proto_rawDescGZIP() []byte {
	file_continuous_query_proto_instapost_proto_rawDescOnce.Do(func() {
		file_continuous_query_proto_instapost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_continuous_query_proto_instapost_proto_rawDesc), len(file_continuous_query_proto_instapost_proto_rawDesc)))
	})
	return file_continuous_query_proto_instapost_proto_rawDescData
}

var file_continuous_query_proto_instapost_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_continuous_query_proto_instapost_proto_goTypes = []any{
	(*InstaPost)(nil), // 0: tutorial.InstaPost
}
var file_continuous_query_proto_instapost_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_continuous_query_proto_instapost_proto_init() }
func file_continuous_query_proto_instapost_proto_init() {
	if File_continuous_query_proto_instapost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_continuous_query_proto_instapost_proto_rawDesc), len(file_continuous_query_proto_instapost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_continuous_query_proto_instapost_proto_goTypes,
		DependencyIndexes: file_continuous_query_proto_instapost_proto_depIdxs,
		MessageInfos:      file_continuous_query_proto_instapost_proto_msgTypes,
	}.Build()
	File_continuous_query_proto_instapost_proto = out.File
	file_continuous_query_proto_instapost_proto_goTypes = nil
	file_continuous_query_proto_instapost_proto_depIdxs = nil
}
