version: '3.8'

services:
  infinispan:
    image: quay.io/infinispan-test/server:main
    container_name: infinispan
    environment:
      USER: admin
      PASS: password
    volumes:
      - ./infinispan-basic-auth.xml:/user-config/infinispan-basic-auth.xml
    command: -c infinispan.xml -c /user-config/infinispan-basic-auth.xml
    ports:
      - "11222:11222"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - infinispan
