// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: query/proto/person.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	BornYear      int32                  `protobuf:"varint,3,opt,name=bornYear,proto3" json:"bornYear,omitempty"`
	BornIn        string                 `protobuf:"bytes,4,opt,name=bornIn,proto3" json:"bornIn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_query_proto_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_query_proto_person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Person) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Person) GetBornYear() int32 {
	if x != nil {
		return x.BornYear
	}
	return 0
}

func (x *Person) GetBornIn() string {
	if x != nil {
		return x.BornIn
	}
	return ""
}

var File_query_proto_person_proto protoreflect.FileDescriptor

const file_query_proto_person_proto_rawDesc = "" +
	"\n" +
	"\x18query/proto/person.proto\x12\btutorial\"v\n" +
	"\x06Person\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12\x1a\n" +
	"\bbornYear\x18\x03 \x01(\x05R\bbornYear\x12\x16\n" +
	"\x06bornIn\x18\x04 \x01(\tR\x06bornInB)Z'infinispan.org/tutorials/go/query/protob\x06proto3"

var (
	file_query_proto_person_proto_rawDescOnce sync.Once
	file_query_proto_person_proto_rawDescData []byte
)

func file_query_proto_person_proto_rawDescGZIP() []byte {
	file_query_proto_person_proto_rawDescOnce.Do(func() {
		file_query_proto_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_person_proto_rawDesc), len(file_query_proto_person_proto_rawDesc)))
	})
	return file_query_proto_person_proto_rawDescData
}

var file_query_proto_person_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_query_proto_person_proto_goTypes = []any{
	(*Person)(nil), // 0: tutorial.Person
}
var file_query_proto_person_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_query_proto_person_proto_init() }
func file_query_proto_person_proto_init() {
	if File_query_proto_person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_person_proto_rawDesc), len(file_query_proto_person_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_proto_person_proto_goTypes,
		DependencyIndexes: file_query_proto_person_proto_depIdxs,
		MessageInfos:      file_query_proto_person_proto_msgTypes,
	}.Build()
	File_query_proto_person_proto = out.File
	file_query_proto_person_proto_goTypes = nil
	file_query_proto_person_proto_depIdxs = nil
}
