// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: spatial-queries/proto/restaurant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Restaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Score         float32                `protobuf:"fixed32,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_spatial_queries_proto_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_spatial_queries_proto_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_spatial_queries_proto_restaurant_proto_rawDescGZIP(), []int{0}
}

func (x *Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Restaurant) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Restaurant) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Restaurant) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_spatial_queries_proto_restaurant_proto protoreflect.FileDescriptor

const file_spatial_queries_proto_restaurant_proto_rawDesc = "" +
	"\n" +
	"&spatial-queries/proto/restaurant.proto\x12\btutorial\"\xac\x01\n" +
	"\n" +
	"Restaurant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x02R\x05scoreB3Z1infinispan.org/tutorials/go/spatial-queries/protob\x06proto3"

var (
	file_spatial_queries_proto_restaurant_proto_rawDescOnce sync.Once
	file_spatial_queries_proto_restaurant_proto_rawDescData []byte
)

func file_spatial_queries_proto_restaurant_proto_rawDescGZIP() []byte {
	file_spatial_queries_proto_restaurant_proto_rawDescOnce.Do(func() {
		file_spatial_queries_proto_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spatial_queries_proto_restaurant_proto_rawDesc), len(file_spatial_queries_proto_restaurant_proto_rawDesc)))
	})
	return file_spatial_queries_proto_restaurant_proto_rawDescData
}

var file_spatial_queries_proto_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spatial_queries_proto_restaurant_proto_goTypes = []any{
	(*Restaurant)(nil), // 0: tutorial.Restaurant
}
var file_spatial_queries_proto_restaurant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spatial_queries_proto_restaurant_proto_init() }
func file_spatial_queries_proto_restaurant_proto_init() {
	if File_spatial_queries_proto_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spatial_queries_proto_restaurant_proto_rawDesc), len(file_spatial_queries_proto_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spatial_queries_proto_restaurant_proto_goTypes,
		DependencyIndexes: file_spatial_queries_proto_restaurant_proto_depIdxs,
		MessageInfos:      file_spatial_queries_proto_restaurant_proto_msgTypes,
	}.Build()
	File_spatial_queries_proto_restaurant_proto = out.File
	file_spatial_queries_proto_restaurant_proto_goTypes = nil
	file_spatial_queries_proto_restaurant_proto_depIdxs = nil
}
