// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: spatial-queries/proto/trainroute.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrainRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DepartureLat  float64                `protobuf:"fixed64,2,opt,name=departureLat,proto3" json:"departureLat,omitempty"`
	DepartureLon  float64                `protobuf:"fixed64,3,opt,name=departureLon,proto3" json:"departureLon,omitempty"`
	ArrivalLat    float64                `protobuf:"fixed64,4,opt,name=arrivalLat,proto3" json:"arrivalLat,omitempty"`
	ArrivalLon    float64                `protobuf:"fixed64,5,opt,name=arrivalLon,proto3" json:"arrivalLon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainRoute) Reset() {
	*x = TrainRoute{}
	mi := &file_spatial_queries_proto_trainroute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRoute) ProtoMessage() {}

func (x *TrainRoute) ProtoReflect() protoreflect.Message {
	mi := &file_spatial_queries_proto_trainroute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRoute.ProtoReflect.Descriptor instead.
func (*TrainRoute) Descriptor() ([]byte, []int) {
	return file_spatial_queries_proto_trainroute_proto_rawDescGZIP(), []int{0}
}

func (x *TrainRoute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrainRoute) GetDepartureLat() float64 {
	if x != nil {
		return x.DepartureLat
	}
	return 0
}

func (x *TrainRoute) GetDepartureLon() float64 {
	if x != nil {
		return x.DepartureLon
	}
	return 0
}

func (x *TrainRoute) GetArrivalLat() float64 {
	if x != nil {
		return x.ArrivalLat
	}
	return 0
}

func (x *TrainRoute) GetArrivalLon() float64 {
	if x != nil {
		return x.ArrivalLon
	}
	return 0
}

var File_spatial_queries_proto_trainroute_proto protoreflect.FileDescriptor

const file_spatial_queries_proto_trainroute_proto_rawDesc = "" +
	"\n" +
	"&spatial-queries/proto/trainroute.proto\x12\btutorial\"\xa8\x01\n" +
	"\n" +
	"TrainRoute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fdepartureLat\x18\x02 \x01(\x01R\fdepartureLat\x12\"\n" +
	"\fdepartureLon\x18\x03 \x01(\x01R\fdepartureLon\x12\x1e\n" +
	"\n" +
	"arrivalLat\x18\x04 \x01(\x01R\n" +
	"arrivalLat\x12\x1e\n" +
	"\n" +
	"arrivalLon\x18\x05 \x01(\x01R\n" +
	"arrivalLonB3Z1infinispan.org/tutorials/go/spatial-queries/protob\x06proto3"

var (
	file_spatial_queries_proto_trainroute_proto_rawDescOnce sync.Once
	file_spatial_queries_proto_trainroute_proto_rawDescData []byte
)

func file_spatial_queries_proto_trainroute_proto_rawDescGZIP() []byte {
	file_spatial_queries_proto_trainroute_proto_rawDescOnce.Do(func() {
		file_spatial_queries_proto_trainroute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spatial_queries_proto_trainroute_proto_rawDesc), len(file_spatial_queries_proto_trainroute_proto_rawDesc)))
	})
	return file_spatial_queries_proto_trainroute_proto_rawDescData
}

var file_spatial_queries_proto_trainroute_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spatial_queries_proto_trainroute_proto_goTypes = []any{
	(*TrainRoute)(nil), // 0: tutorial.TrainRoute
}
var file_spatial_queries_proto_trainroute_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spatial_queries_proto_trainroute_proto_init() }
func file_spatial_queries_proto_trainroute_proto_init() {
	if File_spatial_queries_proto_trainroute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spatial_queries_proto_trainroute_proto_rawDesc), len(file_spatial_queries_proto_trainroute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spatial_queries_proto_trainroute_proto_goTypes,
		DependencyIndexes: file_spatial_queries_proto_trainroute_proto_depIdxs,
		MessageInfos:      file_spatial_queries_proto_trainroute_proto_msgTypes,
	}.Build()
	File_spatial_queries_proto_trainroute_proto = out.File
	file_spatial_queries_proto_trainroute_proto_goTypes = nil
	file_spatial_queries_proto_trainroute_proto_depIdxs = nil
}
