version: '3.1'

services:
  keycloak:
    image:  quay.io/keycloak/keycloak
    volumes:
      - ./infinispan-keycloak-realm.json:/opt/keycloak/data/import/infinispan-keycloak-realm.json
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: keycloak
      KEYCLOAK_ADMIN_PASSWORD: keycloak
    command: ['start-dev', '--import-realm']
    network_mode: host

  infinispan-server:
    # Console fails with 15.0.11.Final. Fix will land in Infinispan 15.0.12.Final
    image: quay.io/infinispan/server:15.0.8.Final
    volumes:
      - ./infinispan-token-realm.yaml:/user-config/infinispan-token-realm.yaml
    depends_on:
      - "keycloak"
    container_name: ispn
    environment:
      USER: admin
      PASS: password
    command: -c infinispan.xml -c /user-config/infinispan-token-realm.yaml
    network_mode: host
