name: Add release label to closed issues
# This GitHub Actions workflow automatically adds the current release as a label to closed
# issues with pull requests that were merged. The value of the current
# release is held in a GitHub organization variable. The GHA also handles backports on
# the 16.0 and 16.1 branches.

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  add-release-label:
    runs-on: ubuntu-latest
    outputs:
      issue_urls: ${{ steps.get_linked_issue.outputs.issue_urls }}
      # An array of issue URLs fixed by the merged PR
      issue_label: ${{ steps.get_label.outputs.issue_label }}
      # The label to use based on the branch

    steps:
      - name: Get issue(s) linked to merged PR
        if: ${{ github.event.pull_request && github.event.pull_request.merged }}
        # Only run if the PR was merged
        id: get_linked_issue
        shell: bash
        env:
          GH_TOKEN: "${{ secrets.INFINISPAN_RELEASE_TOKEN }}"
        run: >
          echo issue_urls="$(node -pe "try{obj=JSON.parse(
          '$(gh pr view ${{ github.event.pull_request.html_url }} --json closingIssuesReferences)'
          );
          obj.closingIssuesReferences.map(issue => issue.url).toString().replaceAll(',',' ')}
          catch(TypeError){}")" >> "$GITHUB_OUTPUT"

      - name: Create label and ignore error if it exists
        id: get_label
        shell: bash
        env:
          GH_TOKEN: "${{ secrets.INFINISPAN_RELEASE_TOKEN }}"
        continue-on-error: true
        run: >
          label="release/${{ vars.RELEASE }}";
          echo "issue_label=${label}" >> "$GITHUB_OUTPUT";
          gh label create -f "release/${label}"
          --color "#0E8A16";

      - name: Label issue(s)
        shell: bash
        env:
          GH_TOKEN: "${{ secrets.INFINISPAN_RELEASE_TOKEN }}"
        run: >
          declare -a arr=(${{ steps.get_linked_issue.outputs.issue_urls }});
          for issue in "${arr[@]}";
          do gh issue edit "$issue" --add-label "${{ steps.get_label.outputs.issue_label }}";
          done;

