= Distributed Cache with Embedded Infinispan
:summary: Create a distributed cache across a cluster of embedded Infinispan nodes using DIST_SYNC mode
:mode: embedded
:topics: caching,clustering
:keywords: distributed,cluster,embedded,cache-mode,dist-sync,partitioned
:duration: 10
:source-dir: infinispan-embedded/cache-distributed

TIP: The source code for this tutorial is available on link:https://github.com/infinispan/infinispan-simple-tutorials/tree/main/{source-dir}[GitHub].

== What You Will Learn

How to create a clustered Infinispan cache manager in embedded mode, configure a distributed (partitioned) cache, and observe how data is distributed across cluster nodes.

== Prerequisites

* Java 17+

== Step 1: Add the Embedded Dependency

Add Infinispan core to your `pom.xml`:

[source,xml]
----
<dependency>
   <groupId>org.infinispan</groupId>
   <artifactId>infinispan-core</artifactId>
</dependency>
----

== Step 2: Create a Clustered Cache Manager

Use `GlobalConfigurationBuilder.defaultClusteredBuilder()` to enable JGroups clustering:

[source,java]
----
include::src/main/java/org/infinispan/tutorial/simple/distributed/InfinispanDistributed.java[tag=clustered-cache-manager]
----

This starts a JGroups cluster. Multiple instances on the same network will auto-discover each other.

== Step 3: Configure a Distributed Cache

Create a cache with `DIST_SYNC` mode. In this mode, data is partitioned: each entry is stored on a subset of nodes (by default 2 copies):

[source,java]
----
include::src/main/java/org/infinispan/tutorial/simple/distributed/InfinispanDistributed.java[tag=distributed-cache]
----

== Step 4: Populate and Query the Cache

Store entries and observe ownership. Use `Flag.CACHE_MODE_LOCAL` to see only entries owned by the local node:

[source,java]
----
include::src/main/java/org/infinispan/tutorial/simple/distributed/InfinispanDistributed.java[tag=display-cache]
----

== Step 5: Run the Tutorial

[source,bash]
----
mvn package exec:java
----

The local view will show fewer entries than the cluster-wide view because distributed mode partitions data across nodes.

== What's Next

* Try link:/tutorials/embedded-cache-replicated/[replicated mode] where every node has all data
* Add link:/tutorials/embedded-listeners/[cache listeners] to react to changes
* Use link:/tutorials/embedded-streams/[distributed streams] for parallel processing
